In [1]:
import pandas as pd
import numpy as np

In [2]:
bios = pd.read_csv('bios2.csv')

In [3]:
df = bios

In [4]:
df.drop('Name order',axis = 1,inplace =True)

In [5]:
df.drop('Original name',axis = 1, inplace = True)

In [6]:
df.drop('Other names', axis = 1, inplace =True)
df.drop('Title(s)',axis = 1, inplace = True)

In [7]:
# Extract Height (ending with 'cm') and Weight (ending with 'kg') from 'Measurements'
df['Height'] = df['Measurements'].str.extract(r'(\d+)\s*cm')
df['Weight'] = df['Measurements'].str.extract(r'(\d+)\s*kg')

In [8]:
df['Height'] = df['Height'].str.replace(' kg', '', regex=True)
df['Weight'] = df['Weight'].str.replace(' cm', '', regex=True)

In [9]:
df['Height'] = df['Height'].astype(float)
df['Weight'] = df['Weight'].astype(float)

In [10]:
#Now we will be parse out date of birh and date of death from the 'Birth' and 'Death' columns
df['Date_of_birth'] = df['Born'].str.extract(r'(\b\d{1,2} (?:January|February|March|April|May|June|July|August|September|October|November|December) \d{4}\b)')
#Using GPT to write the regex expression. Useful, and then try it out on regex101.com

In [11]:
# convet karege abb hum date of birth ko datetime format mein
df['Date_of_birth'] = pd.to_datetime(df['Date_of_birth'])

In [12]:
# abb zara dob mein se month vaera ka column banadete hain
df['Month_of_birth'] = df['Date_of_birth'].dt.month

In [13]:
# abb hum marne ki date nikalege :
df['Date_of_death'] = df['Died'].str.extract(r'(\b\d{1,2} (?:January|February|March|April|May|June|July|August|September|October|November|December) \d{4}\b)')

In [14]:
df['Date_of_death'] = pd.to_datetime(df['Date_of_death'])

In [15]:
df['Moth_of_death'] = df['Date_of_death'].dt.month

In [16]:
df

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Nationality,Height,Weight,Date_of_birth,Month_of_birth,Date_of_death,Moth_of_death
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,1886-12-12,12.0,1960-10-02,10.0
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,183.0,76.0,1969-04-01,4.0,NaT,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,183.0,76.0,1898-08-13,8.0,1994-07-17,7.0
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,168.0,64.0,1895-05-11,5.0,1978-03-20,3.0
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,1878-04-17,4.0,1930-07-25,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,Competed in Olympic Games,Female,Polina•Luchnikova,Polina•Luchnikova,"30 January 2002 in Serov, Sverdlovsk (RUS)",NaN,ROC,149222,167 cm / 61 kg,"Agidel, Ufa (RUS)",NaN,NaN,167.0,61.0,2002-01-30,1.0,NaT,NaN
145496,Competed in Olympic Games,Female,Valeriya Sergeyevna•Merkusheva,Valeriya•Merkusheva,"20 September 1999 in Moskva (Moscow), Moskva (...",NaN,ROC,149223,168 cm / 65 kg,"SKIF Nizhny Novgorod, Nizhny Novgorod (RUS)",NaN,NaN,168.0,65.0,1999-09-20,9.0,NaT,NaN
145497,Competed in Olympic Games,Female,Yuliya•Smirnova,Yuliya•Smirnova,"8 May 1998 in Kotlas, Arkhangelsk (RUS)",NaN,ROC,149224,163 cm / 55 kg,"Agidel, Ufa (RUS)",NaN,NaN,163.0,55.0,1998-05-08,5.0,NaT,NaN
145498,Competed in Olympic Games,Male,André•Foussard,André•Foussard,"19 May 1899 in Niort, Deux-Sèvres (FRA)","18 March 1986 in Niort, Deux-Sèvres (FRA)",France,149225,166 cm,"Beauvoisine FC, Rouen (FRA)",NaN,NaN,166.0,NaN,1899-05-19,5.0,1986-03-18,3.0
145499,Non-starter • Administrator,Male,"William Berge ""Bill""•Phillips",Bill•Phillips,"15 July 1913 in Dulwich Hill, New South Wales ...","20 October 2003 in Sydney, New South Wales (AUS)",Australia,149814,NaN,NaN,NaN,NaN,NaN,NaN,1913-07-15,7.0,2003-10-20,10.0

In [17]:
"""
And this how we clean the data 

"""

columns_to_keep = ['athlete_id','Full name','Born','NOC','Height','Weight','Date_of_birth',
                       'Month_of_birth','Date_of_death','Moth_of_death']

df = df[columns_to_keep]

In [18]:
df

,athlete_id,Full name,Born,NOC,Height,Weight,Date_of_birth,Month_of_birth,Date_of_death,Moth_of_death
0,1,"François Joseph Marie Antoine ""Jean-François""•...","12 December 1886 in Bordeaux, Gironde (FRA)",France,NaN,NaN,1886-12-12,12.0,1960-10-02,10.0
1,2,Arnaud Benjamin•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",France,183.0,76.0,1969-04-01,4.0,NaT,NaN
2,3,Jean Laurent Robert•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...",France,183.0,76.0,1898-08-13,8.0,1994-07-17,7.0
3,4,Jacques Marie Stanislas Jean•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)",France,168.0,64.0,1895-05-11,5.0,1978-03-20,3.0
4,5,Henry Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)",France,NaN,NaN,1878-04-17,4.0,1930-07-25,7.0
...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina•Luchnikova,"30 January 2002 in Serov, Sverdlovsk (RUS)",ROC,167.0,61.0,2002-01-30,1.0,NaT,NaN
145496,149223,Valeriya Sergeyevna•Merkusheva,"20 September 1999 in Moskva (Moscow), Moskva (...",ROC,168.0,65.0,1999-09-20,9.0,NaT,NaN
145497,149224,Yuliya•Smirnova,"8 May 1998 in Kotlas, Arkhangelsk (RUS)",ROC,163.0,55.0,1998-05-08,5.0,NaT,NaN
145498,149225,André•Foussard,"19 May 1899 in Niort, Deux-Sèvres (FRA)",France,166.0,NaN,1899-05-19,5.0,1986-03-18,3.0
145499,149814,"William Berge ""Bill""•Phillips","15 July 1913 in Dulwich Hill, New South Wales ...",Australia,NaN,NaN,1913-07-15,7.0,2003-10-20,10.0

In [19]:
df.to_csv('bios_cleaned.csv', index=False)